import streamlit as st


ptsc_description = """
The engine powering **The Been Project** is called **ptsc**, which stands for *Positive Trading Strategies Classification*. 
It is an infrastructure designed to optimize a large set of parameters in order to successfully classify positive future trades. 
This self-optimizing system leverages machine learning models to improve its performance over time.

The current application serves as a user-friendly interface to view and interact with the results generated by **ptsc**.
"""

question_description = """
The app is designed to answer the following key questions:

-  How are the signals and their properties (strength, performance) distributed over time?
-  What is the optimal signal threshold for decision making?
-  How random are the positive signals? Analyzing randomness and consistency over time.
-  How does the win rate evolve over time during uptrends? Specifically, how much additional win rate does the system provide compared to the benchmark?
-  Does the investment performance outperform the benchmark overall?
"""


def show_welcome_page():
    st.title("Welcome!")
    st.markdown(ptsc_description)
    st.markdown(question_description)
 #   st.write("Please note that in order to see")
